services:
  tunnel:
    image: cloudflare/cloudflared:latest
    network_mode: host
    restart: unless-stopped
    env_file:
      - .env
    entrypoint: ["cloudflared", "tunnel", "--no-autoupdate", "run", "--token", "eyJhIjoiMjBhYWU3OWZjZjI4MmYwZWE5YjAyMTEyNzhkNDEwNDAiLCJ0IjoiYmUzY2E1MDUtMDIxOS00MDM2LWFlZjUtY2Y5NWRhMGM1Nzg5IiwicyI6IlpHWmxPR013TmpFdE5UUmhNaTAwWlRZMExUaGhNMlF0T0RSaFl6RmtaakUzWVRFMiJ9"]
    container_name: cloudflared-tunnel

  service:
    build: .
    container_name: linebot-service
    ports:
      - "8000:8000"  # 映射 FastAPI 服務的端口
    env_file:
      - .env
    volumes:
      - .:/app  # 將當前目錄映射到容器中的 /app 目錄

# volumes:
  # app-data: